
name: PHPUnit
on:
  push:
    branches-ignore:
      - 9.x-4.x

jobs:
  run-tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "8.0"
          - "8.1"
        pgsql-version:
          - "13"
        drupal-version:
          - "9.2.x-dev"
          - "9.3.x-dev"
          - "9.4.x-dev"
          - "9.5.x-dev"
          - "10.0.x-dev"
        exclude:
          - php-version: "8.0"
            pgsql-version: "13"
            drupal-version: "10.0.x-dev"
          - php-version: "8.1"
            pgsql-version: "13"
            drupal-version: "9.2.x-dev"

    steps:
      # Check out the repo
      - name: Checkout Repository
        uses: actions/checkout@v2
      # Here we fully  build a docker using the current checked out code
      # to ensure we have not broken the install/build process.
      - name: Build Dockerfile-php8.1-pgsql13
        if: ${{ matrix.php-version == '8.1' && matrix.pgsql-version == '13'}}
        run: |
          docker build --tag=tripaldocker:localdocker \
            --build-arg drupalversion="${{ matrix.drupal-version }}" \
            --build-arg chadoschema='testchado' ./ \
            --file tripaldocker/Dockerfile-php8.1-pgsql13
      - name: Build Dockerfile-php8-pgsql13
        if: ${{ matrix.php-version == '8.0' && matrix.pgsql-version == '13'}}
        run: |
          docker build --tag=tripaldocker:localdocker \
            --build-arg drupalversion="${{ matrix.drupal-version }}" \
            --build-arg chadoschema='testchado' ./ \
            --file tripaldocker/Dockerfile-php8-pgsql13
      # Just spin up docker the good ol' fashion way.
      - name: Spin up Local Docker
        run: |
          docker run --publish=80:80 --name=tripaldocker -tid \
            --volume=`pwd`:/var/www/drupal9/web/modules/contrib/tripal \
            tripaldocker:localdocker
          docker exec tripaldocker service postgresql restart
      # Runs the PHPUnit tests.
      - name: Run PHPUnit Tests
        env:
          SIMPLETEST_BASE_URL: "http://localhost"
          SIMPLETEST_DB: "pgsql://drupaladmin:drupal9developmentonlylocal@localhost/sitedb"
          BROWSER_OUTPUT_DIRECTORY: "/var/www/drupal9/web/sites/default/files/simpletest"
        run: |
          docker exec tripaldocker service postgresql restart
          docker exec -e SIMPLETEST_BASE_URL=$SIMPLETEST_BASE_URL \
            -e SIMPLETEST_DB=$SIMPLETEST_DB \
            -e BROWSER_OUTPUT_DIRECTORY=$BROWSER_OUTPUT_DIRECTORY \
            --workdir=/var/www/drupal9/web/modules/contrib/tripal \
            tripaldocker phpunit
