# Run some PHPUnit tests
name: PHPUnit-Tests

# When do we want the tests to run?
on: [push, pull_request]

# Define jobs that are part of the workflow
jobs:
  # Job 1: 'build'
  run-tests:
    # Runner type
    runs-on: ubuntu-latest
    # PHP Targets
    strategy:
      matrix:
        drupalversion: ['8.9.x-dev', '9.0.x-dev', '9.1.x-dev']
    # Give the builds names so we can tell them apart
    name: PHPUnit Drupal ${{ matrix.drupalversion }}

    # Steps in the sequence
    steps:
      # Check out the repo
      - name: Checkout Repository
        uses: actions/checkout@v2
      # Here we fully  build a docker using the current checked out code
      # to ensure we have not broken the install/build process.
      - name: Build the Docker
        run: |
          docker build --tag=tripaldocker:localdocker --build-arg drupalversion='${{ matrix.drupalversion }}' tripaldocker/
      # Just spin up docker the good ol' fashion way.
      - name: Spin up Local Docker
        run: |
          docker run --publish=80:80 --name=tripaldocker -tid \
            --volume=`pwd`:/var/www/drupal8/web/modules/contrib/tripal \
            tripaldocker:localdocker
          docker exec tripaldocker service postgresql restart
      # Now prepare the new docker container for running tests.
      # We specifically do not have a `chado` named schema to test that
      # an assumption hasn't been made here.
      - name: Prep Local Docker for Tests
        run: |
          docker exec tripaldocker drush cr
          docker exec tripaldocker drush trp-drop-chado --schema-name=chado
          docker exec tripaldocker drush trp-prep-tests
      # Drupal 9.1.x needs prophecy-phpunit due to https://www.drupal.org/project/drupal/issues/3182653
      - name: Add prophecy-phpunit
        if: ${{ matrix.drupalversion == '9.1.x-dev' }}
        run: |
          docker exec --workdir /var/www/drupal8 tripaldocker composer require phpspec/prophecy-phpunit
      # Runs the PHPUnit tests.
      # https://github.com/mheap/phpunit-github-actions-printer is used
      # to report PHPUnit fails in a meaningful way to github in PRs.
      # Stopped using mheap due to warning w/ phpunit8->9
      - name: Run PHPUnit Tests
        env:
          SIMPLETEST_BASE_URL: "http://localhost"
          SIMPLETEST_DB: "pgsql://drupaladmin:drupal8developmentonlylocal@localhost/sitedb"
          BROWSER_OUTPUT_DIRECTORY: "/var/www/drupal8/web/sites/default/files/simpletest"
        run: |
          docker exec tripaldocker service postgresql restart
          docker exec -e SIMPLETEST_BASE_URL=$SIMPLETEST_BASE_URL \
            -e SIMPLETEST_DB=$SIMPLETEST_DB \
            -e BROWSER_OUTPUT_DIRECTORY=$BROWSER_OUTPUT_DIRECTORY \
            --workdir=/var/www/drupal8/web/modules/contrib/tripal \
            tripaldocker phpunit
